source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'CCWeiboSwiftApp' do
	pod 'ActiveLabel', '~> 0.7.1'
	pod 'Alamofire', '~> 4.2.0'
	pod 'Cartography', '~> 1.0.1'
	pod 'SwiftyJSON', '~> 3.1.4'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'MJRefresh', '~> 3.1.12'
	pod 'SDWebImage', '~> 3.8.2'
	pod 'TZImagePickerController', '~> 1.7.8'
end
