source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'CCWeiboSwiftApp' do
    #Swift
	pod 'ActiveLabel', '~> 0.7.1'
	pod 'Alamofire', '~> 4.5.0'
	pod 'Cartography', '~> 1.1.0'
	pod 'SwiftyJSON', '~> 3.1.4'
    
    #Objective-C
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'MJRefresh', '~> 3.1.12'
	pod 'SDWebImage', '~> 3.8.2'
	pod 'TZImagePickerController', '~> 1.8.1'
end
