source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'CCWeiboAPP' do
	pod 'Cartography', '~> 0.5.0'
	pod 'Alamofire', '~> 3.4'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'SDWebImage', '~>3.8'
end