source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'CCWeiboAPP' do
	pod 'ActiveLabel', '~> 0.6.2'
	pod 'Alamofire', '~> 4.0.0'
	pod 'Cartography', '~> 0.7.0'
	pod 'SwiftyJSON', '~> 3.0.0'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'MJRefresh', '~> 3.1.12'
	pod 'SDWebImage', '~> 3.8.2'
	pod 'TZImagePickerController', '~> 1.6.7'
end